"use client"
import { useState } from "react"
import { motion, AnimatePresence } from "framer-motion"
import { ChevronRight } from "lucide-react"

const categories = [
  { id: "GENERAL", label: "GENERAL" },
  { id: "DATA", label: "DATA / NETWORKS" },
  { id: "PAYMENTS", label: "PAYMENTS / WALLET" },
]

const faqData = {
  GENERAL: [
    {
      question: "Which platforms do you support?",
      answer: "We work with all major e-commerce platforms including Flipkart, Amazon, Meesho, JioMart, Myntra, and more. Our team is experienced in handling platform-specific issues and optimizations."
    },
    {
      question: "How will your services solve my online business problems?",
      answer: "We provide complete analysis and reporting on cash flow issues, wrong shipment weight charges, high shipping costs, illegal deductions, and settlement disputes."
    },
    {
      question: "Do I need to share my seller account access?",
      answer: "Yes, for accurate analysis we need limited access or data from your seller accounts. However, your data is 100% secure with us following strict security protocols."
    },
    {
      question: "What are your pricing plans?",
      answer: "Our plans start from just ₹249/month, which includes detailed reporting and expert support. We have different tiers based on the number of platforms."
    },
    {
      question: "How quickly can I see results?",
      answer: "Most clients start seeing improvements within the first month. Our initial audit typically reveals immediate savings from wrong commission recoveries."
    }
  ],
  DATA: [
    {
      question: "How is my data security handled?",
      answer: "We use enterprise-grade encryption for all data storage. Your seller account data is only used for analysis and is never shared with third parties."
    },
    {
      question: "Do you offer API integration for real-time tracking?",
      answer: "Yes, we provide API integration options for major platforms to fetch real-time data for more accurate and timely reporting."
    },
    {
      question: "What kind of network infrastructure do you use?",
      answer: "Our systems run on secure, high-speed cloud infrastructure ensuring 99.9% uptime and fast processing of large volume transaction data."
    },
    {
      question: "Can I export my data and reports?",
      answer: "Absolutely. All reports and analyzed data can be exported in various formats including Excel, CSV, and PDF for your internal records."
    },
    {
      question: "How often is the data synced from platforms?",
      answer: "Data is typically synced every 24 hours, but we can configure high-frequency sync for businesses with large daily transaction volumes."
    }
  ],
  PAYMENTS: [
    {
      question: "How do you track payment discrepancies?",
      answer: "We cross-reference every order with actual bank settlements, identifying missing payments, wrong deductions, or delayed transfers automatically."
    },
    {
      question: "What is the Wallet feature in Speed E-Com?",
      answer: "The Wallet feature tracks your virtual balance across platforms, helping you understand your net receivable amount at any given time."
    },
    {
      question: "How do you handle refund and return adjustments?",
      answer: "Our system tracks every return and ensures that the platform correctly adjusts the commission and shipping fees in your favor."
    },
    {
      question: "Can you help with tax reconciliation?",
      answer: "Yes, we provide detailed reports on GST deductions and TCS/TDS withheld by platforms to simplify your monthly tax filing process."
    },
    {
      question: "What happens if I find a payment error in my report?",
      answer: "Our experts help you raise formal disputes with the respective e-commerce platforms using the detailed evidence generated by our system."
    }
  ]
}

export function FAQ() {
  const [activeCategory, setActiveCategory] = useState("GENERAL")
  const [activeIndex, setActiveIndex] = useState(0)

  const currentFaqs = faqData[activeCategory as keyof typeof faqData]

  return (
    <section id="faq" className="py-12 lg:py-24 bg-white">
      <div className="container mx-auto px-4 lg:px-8">
        {/* Main Heading Center */}
        <div className="text-center mb-16">
          <motion.span
            initial={{ opacity: 0, scale: 0.8 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            className="inline-block px-4 py-1.5 bg-violet-100 text-violet-700 text-sm font-bold rounded-full mb-4 uppercase tracking-wider"
          >
            FAQ
          </motion.span>
          <h2 className="text-3xl lg:text-6xl font-bold font-display mb-4">
            Frequently Asked <span className="text-transparent bg-clip-text bg-gradient-to-r from-violet-600 to-indigo-600">Questions</span>
          </h2>
          <p className="text-base lg:text-xl text-muted-foreground max-w-2xl mx-auto">
            Got questions? We've got answers. If you can't find what you're looking for,
            feel free to contact us directly.
          </p>
        </div>

        {/* Category Tabs */}
        <div className="flex flex-wrap justify-center gap-4 mb-12">
          {categories.map((cat) => (
            <button
              key={cat.id}
              onClick={() => {
                setActiveCategory(cat.id)
                setActiveIndex(0)
              }}
              className={`px-6 py-3 rounded-full font-bold transition-all duration-300 ${
                activeCategory === cat.id
                  ? "bg-violet-600 text-white shadow-lg"
                  : "bg-slate-100 text-slate-600 hover:bg-slate-200"
              }`}
            >
              {cat.label}
            </button>
          ))}
        </div>

        <div className="grid lg:grid-cols-12 gap-8 items-start max-w-7xl mx-auto">
          {/* Left Side - Questions */}
          <div className="lg:col-span-5 space-y-3">
            {currentFaqs.map((faq, index) => (
              <motion.button
                key={`${activeCategory}-${index}`}
                onClick={() => setActiveIndex(index)}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: index * 0.1 }}
                className={`w-full text-left p-4 lg:p-6 rounded-2xl transition-all duration-300 flex items-center justify-between group ${
                  activeIndex === index
                    ? "bg-gradient-to-r from-violet-600 to-indigo-600 text-white shadow-xl shadow-violet-200 scale-[1.02]"
                    : "bg-slate-50 hover:bg-slate-100 text-slate-700 border border-slate-100"
                }`}
              >
                <span className={`font-bold text-sm lg:text-lg pr-4 ${activeIndex === index ? "text-white" : "text-slate-900 group-hover:text-violet-600"}`}>
                  {faq.question}
                </span>
                <ChevronRight 
                  className={`w-5 h-5 flex-shrink-0 transition-transform duration-300 ${
                    activeIndex === index ? "rotate-0 text-white" : "-rotate-90 text-slate-400 group-hover:text-violet-600"
                  }`} 
                />
              </motion.button>
            ))}
          </div>

          {/* Right Side - Answer */}
          <div className="lg:col-span-7 h-full">
            <div className="bg-slate-50/50 border border-slate-100 rounded-[2rem] p-8 lg:p-12 min-h-[300px] lg:min-h-[400px] flex items-center sticky top-32">
              <AnimatePresence mode="wait">
                <motion.div
                  key={`${activeCategory}-${activeIndex}`}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -20 }}
                  transition={{ duration: 0.3 }}
                  className="space-y-6"
                >
                  <div className="w-12 h-1 bg-gradient-to-r from-violet-600 to-indigo-600 rounded-full" />
                  <h3 className="text-2xl lg:text-4xl font-bold text-slate-900 leading-tight">
                    {currentFaqs[activeIndex].question}
                  </h3>
                  <p className="text-lg lg:text-xl text-slate-600 leading-relaxed">
                    {currentFaqs[activeIndex].answer}
                  </p>
                 
                </motion.div>
              </AnimatePresence>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

